<!-- PAGE HEADER
    ============================== -->
    <div class="page__header">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h3 class="page-header__title"><i class="fa fa-book"></i> Документация</h3>
            
          </div>
        </div>
      </div>
    </div>


    <!-- PAGE CONTENT
    ============================== -->
    <div class="container section section_alt">
      <div class="row">
        <div class="col-md-8 col-md-offset-2" id="tree">
          <div class="col-md-6">
            <h2>
              <a href="/category" class="features__title">
                fsaas dsd
              </a>
            </h2>
            <span class="features__intro">
              asdasda sddf sdf sdf sdf sdfsdfsdf
            </span>
          </div>
          <div class="col-md-6">
            <h2>
              <a href="#" class="features__title">
                fsaas dsd
              </a>
            </h2>
            <span class="features__intro">
              asdasda sddf sdf sdf sdf sdfsdfsdf
            </span>
          </div>
          <div class="col-md-6">
            <h2>
              <a href="#" class="features__title">
                fsaas dsd
              </a>
            </h2>
            <span class="features__intro">
              asdasda sddf sdf sdf sdf sdfsdfsdf
            </span>
          </div>
          <div class="col-md-6">
            <h2>
              <a href="#" class="features__title">
                fsaas dsd
              </a>
            </h2>
            <span class="features__intro">
              asdasda sddf sdf sdf sdf sdfsdfsdf
            </span>
          </div>
          <div class="col-md-6">
            <h2>
              <a href="#" class="features__title">
                fsaas dsd
              </a>
            </h2>
            <span class="features__intro">
              asdasda sddf sdf sdf sdf sdfsdfsdf
            </span>
          </div>
          <div class="col-md-6">
            <h2>
              <a href="#" class="features__title">
                fsaas dsd
              </a>
            </h2>
            <span class="features__intro">
              asdasda sddf sdf sdf sdf sdfsdfsdf
            </span>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
    
