<!-- PAGE HEADER
    ============================== -->
    <div class="page__header">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h3 class="page-header__title"><i class="fa fa-tag"></i> <?php echo $cat['name'] ?></h3>
            <ol class="breadcrumb page-header__breadcrumb">
              <li><a href="index.html">PlaceView</a></li>
              <li class="active"><?php echo $cat['name'] ?></li>
            </ol>
          </div>
        </div>
      </div>
    </div>


    <!-- PAGE CONTENT
    ============================== -->
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="blog__items">
            <?php foreach($docs as $doc): ?>
            <div class="blog__item">
              <img src="/img/general_1.jpg" alt="..." class="img-responsive blog__img hidden-xs">
              <div class="blog__content">
                <h3 class="blog__title">
                  <?php echo $this->tag->linkTo([
                      [
                          'for' => 'docs',
                          'language' =>  $this->config->lang,
                          'article' => $doc['slug']
                      ],
                      $doc['name']
                  ]) ?>
                </h3>
                <ul class="blog__info">
                  <li><time datetime="2015-01-30"><?php echo $doc['created_at'] ?></time></li>
                  <li>
                    <?php echo $this->tag->linkTo([
                        [
                            'for' => 'category',
                            'language' =>  $this->config->lang,
                            'slug' => $cat['slug']
                        ],
                        $cat['name']
                    ]) ?>
                  </li>
                  <li><a href="#"><i class="fa fa-comments-o"></i> Обсудить</a></li>
                </ul>
                <div class="blog__body">
                  <?php echo $doc['text'] ?>
                </div>
              </div>
            </div> <!-- / .blog__item -->
            <?php endforeach ?>
            <div class="blog__item">
              <img src="/img/general_2.jpg" alt="..." class="img-responsive blog__img hidden-xs">
              <div class="blog__content">
                <h3 class="blog__title">
                  <a href="blog-post.html">Ut eget purus ut ante imperdiet feugiat quis vel elit. Donec imperdiet enim quis risus</a>
                </h3>
                <ul class="blog__info">
                  <li><time datetime="2015-01-29">January 29, 2015</time></li>
                  <li><a href="#">Bootstrap</a></li>
                  <li><a href="#"><i class="fa fa-comments-o"></i> 4</a></li>
                </ul>
                <div class="blog__body">
                  Nam ultrices, orci sit amet dignissim dignissim, tellus elit consequat dui, eu venenatis urna nisi non est. Aliquam egestas pulvinar ornare. Aenean et vulputate lacus. Ut eget purus ut ante imperdiet feugiat quis vel elit. Donec imperdiet enim quis risus porttitor congue. Vestibulum vel tristique urna. Pellentesque nulla leo, laoreet sed luctus eu, dapibus id lorem. Pellentesque eu tincidunt odio. Proin imperdiet bibendum mauris, ut bibendum odio mollis id.
                </div>
              </div>
            </div> <!-- / .blog__item -->
          </div> <!-- / .blog__items -->
          <!-- Pager -->
          <ul class="pager pull-right">
            <li class="disabled"><a href="#">Previous</a></li>
            <li><a href="#">Next</a></li>
          </ul>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>