  <!-- PAGE HEADER
    ============================== -->
    <div class="page__header">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h3 class="page-header__title"><?=$name?></h3>
            <ol class="breadcrumb page-header__breadcrumb">
              <li><a href="index.html">PlaceView</a></li>
              <li class="active">info</li>
            </ol>
          </div>
        </div>
      </div>
    </div>


    <!-- PAGE CONTENT
    ============================== -->
    <div class="container">
      <div class="row">
        <div class="col-sm-3 col-md-2">

          <!-- Gategories -->
          <h3 class="header">Categories</h3>
          <div class="list-group list-group-left ui__sidebar nav affix-top" id="moving-menu" data-spy="affix">
            <a href="#ui_typography" class="list-group-item">Typography</a>
            <a href="#ui_tables" class="list-group-item">Tables</a>
            <a href="#ui_buttons" class="list-group-item">Buttons</a>
            <a href="#ui_tabs" class="list-group-item">Tabs</a>
            <a href="#ui_pills" class="list-group-item">Pills</a>
            <a href="#ui_pagination" class="list-group-item">Pagination</a>
            <a href="#ui_pager" class="list-group-item">Pager</a>
            <a href="#ui_progress-bars" class="list-group-item">Progress bars</a>
            <a href="#ui_list-groups" class="list-group-item">List groups</a>
            <a href="#ui_panels" class="list-group-item">Panels</a>
            <a href="#ui_accordion" class="list-group-item">Accordion</a>
            <a href="#ui_carousel" class="list-group-item">Carousel</a>
            <a href="#ui_pagination" class="list-group-item">Pagination</a>
            <a href="#ui_pager" class="list-group-item">Pager</a>
            <a href="#ui_progress-bars" class="list-group-item">Progress bars</a>
            <a href="#ui_list-groups" class="list-group-item">List groups</a>
            <a href="#ui_panels" class="list-group-item">Panels</a>
            <a href="#ui_accordion" class="list-group-item">Accordion</a>
            <a href="#ui_carousel" class="list-group-item">Carousel</a>
          </div> <!--  / .list-group -->
        </div>
        <div class="col-sm-9 col-md-10">
          
          <!-- Typography -->
          <div class="ui__section" id="ui_typography">
            <div class="blog__items">
            <div class="blog__item">
              <div class="blog__content">
                <h3 class="blog__title">
                  <a href="blog-post.html">Sed lacinia suscipit lacus non sodales. Pellentesque lacinia ornare justo eu tincidunt</a>
                </h3>
                <ul class="blog__info">
                  <li><time datetime="2015-01-30">January 30, 2015</time></li>
                  <li><a href="#">Bootstrap</a></li>
                  <li><a href="#"><i class="fa fa-comments-o"></i> 2</a></li>
                </ul>
                <div class="blog__body" id="article_info">
                  <img src="/img/general_1.jpg" alt="..." class="img-responsive blog__img">
                  <p>
                    Nam ultrices, orci sit amet dignissim dignissim, tellus elit consequat dui, eu venenatis urna nisi non est. Aliquam egestas pulvinar ornare. Aenean et vulputate lacus. Ut eget purus ut ante imperdiet feugiat quis vel elit. Donec imperdiet enim quis risus porttitor congue. Vestibulum vel tristique urna. Pellentesque nulla leo, laoreet sed luctus eu, dapibus id lorem. Pellentesque eu tincidunt odio. Proin imperdiet bibendum mauris, ut bibendum odio mollis id.
                  </p>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque gravida, est non tempus pharetra, erat velit convallis diam, quis blandit neque nulla a nulla. Quisque fringilla lacinia erat, at maximus erat bibendum quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget efficitur nulla, a egestas mi. Cras hendrerit ipsum in tellus consequat sollicitudin. Quisque felis est, dictum nec ante nec, egestas blandit purus. Donec posuere suscipit arcu, eu ullamcorper turpis lobortis et. Nullam viverra tincidunt elit, ac tempus dui iaculis eu. Vivamus eget urna eu purus ultricies scelerisque. Vivamus laoreet bibendum nunc, in ullamcorper tortor euismod nec. Sed a lobortis purus.
                  </p>
                  <p>
                    Cras lobortis pharetra ante sed sagittis. Ut euismod dignissim massa in sollicitudin. Cras tempus urna ut pellentesque lobortis. Nunc bibendum, lorem a blandit scelerisque, velit erat eleifend risus, et pellentesque libero augue non massa. Donec volutpat dui sed fringilla mattis. Mauris aliquet elementum facilisis. Nullam a ligula nec massa vestibulum efficitur. In cursus lacus ut sapien sodales, ac vestibulum sem pretium. Pellentesque nisi nulla, hendrerit consectetur mi eu, blandit pulvinar eros. Nulla fermentum fermentum ante, eu luctus velit laoreet ut. Fusce nec diam id purus pellentesque mollis venenatis at libero. Suspendisse eu dapibus diam, ac accumsan felis.
                  </p>
                  <p>
                    In condimentum ullamcorper justo, ac accumsan tellus. Sed id maximus libero, ut euismod nisi. In hac habitasse platea dictumst. Pellentesque eget convallis lorem. Nullam eget augue rhoncus odio dictum gravida eget at nisi. Maecenas sit amet magna faucibus, malesuada elit vitae, fringilla erat. Ut sollicitudin, augue eu lacinia sagittis, nulla nisi efficitur risus, id posuere tellus sapien sed nisi.
                  </p>
                </div>
              </div>
            </div> <!-- / .blog__item -->

            <!-- New comment -->
            <div class="comment comment_new">
              <div class="comment__author_img">
                <img class="img-responsive" alt="..." src="img/photo_4.jpg">
              </div>
              <div class="comment__content">
                <form>
                  <div class="form-group">
                    <label for="comment-new__textarea" class="sr-only">Enter your comment</label>
                    <textarea class="form-control" rows="2" id="comment-new__textarea" placeholder="Enter your comment"></textarea>
                  </div>
                  <button type="submit" class="btn btn-primary">Send Comment</button>
                </form>
              </div> <!-- / .comment__content -->
            </div> <!-- / .comment__new -->

            <!-- Comments header -->
            <div class="comment__header">
              <span>List of Comments</span>
            </div>

            <!-- All comments -->
            <div class="comment">
              <div class="comment__author_img">
                <img src="img/photo_1.jpg" alt="..." class="img-responsive">
              </div>
              <div class="comment__content">
                <div class="comment__author_name">John Doe</div>
                <time datetime="2015-01-30" class="comment__date">February 02, 2015</time>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque gravida, est non tempus pharetra, erat velit convallis diam, quis blandit neque nulla a nulla. Quisque fringilla lacinia erat, at maximus erat bibendum quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p>
                <div class="btn-group pull-right" role="group" aria-label="comment__actions">
                  <a href="#" class="btn btn-default btn-xs"><i class="fa fa-times"></i> Remove</a>
                  <a href="#" class="btn btn-default btn-xs"><i class="fa fa-edit"></i> Edit</a>
                  <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-reply"></i> Answer</a>
                </div>
              </div> <!-- / .comment__content -->
            </div> <!-- / .comment -->
            <div class="comment comment_answer_1">
              <div class="comment__author_img">
                <img src="img/photo_2.jpg" alt="..." class="img-responsive">
              </div>
              <div class="comment__content">
                <div class="comment__author_name">Judy Doe</div>
                <time datetime="2015-01-30" class="comment__date">February 02, 2015</time>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque gravida, est non tempus pharetra, erat velit convallis diam, quis blandit neque nulla a nulla. Quisque fringilla lacinia erat, at maximus erat bibendum quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p>
                <div class="btn-group pull-right" role="group" aria-label="comment__actions">
                  <a href="#" class="btn btn-default btn-xs"><i class="fa fa-times"></i> Remove</a>
                  <a href="#" class="btn btn-default btn-xs"><i class="fa fa-edit"></i> Edit</a>
                  <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-reply"></i> Answer</a>
                </div>
              </div> <!-- / .comment__content -->
            </div> <!-- / .comment -->
            <div class="comment comment_answer_2">
              <div class="comment__author_img">
                <img src="img/photo_3.jpg" alt="..." class="img-responsive">
              </div>
              <div class="comment__content">
                <div class="comment__author_name">Richard Roe</div>
                <time datetime="2015-01-30" class="comment__date">February 02, 2015</time>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque gravida, est non tempus pharetra, erat velit convallis diam, quis blandit neque nulla a nulla. Quisque fringilla lacinia erat, at maximus erat bibendum quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p>
                <div class="btn-group pull-right" role="group" aria-label="comment__actions">
                  <a href="#" class="btn btn-default btn-xs"><i class="fa fa-times"></i> Remove</a>
                  <a href="#" class="btn btn-default btn-xs"><i class="fa fa-edit"></i> Edit</a>
                  <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-reply"></i> Answer</a>
                </div>
              </div> <!-- / .comment__content -->
            </div> <!-- / .comment -->
            <div class="comment">
              <div class="comment__author_img">
                <img src="img/photo_4.jpg" alt="..." class="img-responsive">
              </div>
              <div class="comment__content">
                <div class="comment__author_name">John Doe</div>
                <time datetime="2015-01-30" class="comment__date">February 02, 2015</time>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque gravida, est non tempus pharetra, erat velit convallis diam, quis blandit neque nulla a nulla. Quisque fringilla lacinia erat, at maximus erat bibendum quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p>
                <div class="btn-group pull-right" role="group" aria-label="comment__actions">
                  <a href="#" class="btn btn-default btn-xs"><i class="fa fa-times"></i> Remove</a>
                  <a href="#" class="btn btn-default btn-xs"><i class="fa fa-edit"></i> Edit</a>
                  <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-reply"></i> Answer</a>
                </div>
              </div> <!-- / .comment__content -->
            </div> <!-- / .comment -->

          </div>
          </div> <!-- / .ui__section -->
        </div>
      </div> <!-- / .row -->
    </div>
    