<!-- PAGE HEADER
    ============================== -->
<?php $this->partial("widgets/page_header", [
    'header' => $t->_('documentation'),
    'icon' => 'fa-book'
]); ?>

<!-- PAGE CONTENT
============================== -->
<div class="container section section_alt">
    <div class="row">
        <div class="col-md-8 col-md-offset-2" id="tree">
            <?php foreach ($cats as $cat): ?>
                <div class="col-md-6">
                    <h2>
                        <?php echo $this->tag->linkTo([
                            [
                                'for' => 'category',
                                'language' => $this->config->lang,
                                'slug' => $cat['slug']
                            ],
                            $cat['name'],
                            'class' => 'features__title'
                        ]) ?>
                    </h2>
            <span class="features__intro">
              <?php echo $cat['description'] ?>
            </span>
                </div>
            <?php endforeach ?>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
    
