<!-- PAGE HEADER
    ============================== -->
    <div class="page__header">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h3 class="page-header__title"><i class="fa fa-book"></i> Документация</h3>
            
          </div>
        </div>
      </div>
    </div>


    <!-- PAGE CONTENT
    ============================== -->
    <div class="container section section_alt">
      <div class="row">
        <div class="col-md-8 col-md-offset-2" id="tree">
          <?php foreach($cats as $cat): ?>
          <div class="col-md-6">
            <h2>
              <?php echo $this->tag->linkTo([
                  [
                      'for' => 'category',
                      'language' =>  $this->config->lang,
                      'slug' => $cat['slug']
                  ],
                  $cat['name'],
                  'class' => 'features__title'
              ]) ?>
            </h2>
            <span class="features__intro">
              <?php echo $cat['description'] ?>
            </span>
          </div>
          <?php endforeach ?>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
    
