<!-- PAGE HEADER
    ============================== -->
<?php $this->partial("widgets/page_header", [
    'header' => $cat['name'],
    'breadcrumbs' => [
        $cat['name']
    ]
]);

?>

<!-- PAGE CONTENT
============================== -->
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-2">

            <!-- Gategories -->
            <h3 class="header"><?php echo $t->_('cat_list') ?></h3>

            <div class="list-group list-group-left ui__sidebar nav affix-top" id="moving-menu" data-spy="affix">
                <?php foreach ($cats as $_cat): ?>
                    <a href="<?php echo $this->url->get([
                        'for' => 'category',
                        'slug' => $_cat['slug'],
                        'language' => $this->config->lang
                    ]) ?>"
                       class="list-group-item<?php if ($_cat['id'] == $cat['id']): ?> active<?php endif ?>"><?php echo $_cat['name'] ?></a>
                <?php endforeach ?>
            </div>
            <!--  / .list-group -->
        </div>
        <div class="col-sm-9 col-md-10">

            <div class="blog__items">
                <?php if ($docs): ?>
                    <?php foreach ($docs as $doc): ?>
                        <div class="blog__item">
                            <img src="<?php echo $doc['preview_image'] ? $doc['preview_image'] : '/img/general_doc_preview.jpg' ?>" alt="<?php echo $t->_('preview') . ' ' . $doc['name'] ?>" class="img-responsive blog__img hidden-xs">

                            <div class="blog__content">
                                <h3 class="blog__title">
                                    <?php echo $this->tag->linkTo([
                                        [
                                            'for' => 'doc',
                                            'language' => $this->config->lang,
                                            'cat_slug' => $cat['slug'],
                                            'doc_slug' => $doc['slug']
                                        ],
                                        $doc['name']
                                    ]) ?>
                                </h3>
                                <ul class="blog__info">
                                    <?php
                                    $doc['time'] = strtotime($doc['created_at']);
                                    ?>
                                    <li>
                                        <time datetime="<?php echo date('Y-m-d', $doc['time']) ?>"><?php echo date('Y-m-d', $doc['time']) ?></time>
                                    </li>
                                    <?php if ($doc['discuss_url']): ?>
                                        <li>
                                            <a href="<?php echo $doc['discuss_url'] ?>"><i class="fa fa-comments-o"></i> <?php echo $t->_('discuss') ?></a>
                                        </li>
                                    <?php endif ?>
                                </ul>
                                <div class="blog__body">
                                    <?php echo $doc['text'] ?>
                                </div>
                            </div>
                        </div> <!-- / .blog__item -->
                    <?php endforeach ?>
                <?php else: ?>
                    <div class="blog__item">
                        <div class="blog__item"><?php echo $t->_('docs_no_found') ?></div>
                    </div>
                <?php endif ?>
            </div>
            <!-- / .blog__items -->

            <?php if ($maxPages > 1): ?>
                <ul class="pager pull-right">
                    <?php if ($currentPage > 1): ?>
                        <li>
                            <a href="<?php

                            if ($currentPage == 2) {
                                echo $this->url->get([
                                    'for' => 'category',
                                    'slug' => $cat['slug'],
                                    'language' => $this->config->lang
                                ]);
                            } else {
                                echo $this->url->get([
                                    'for' => 'category_page',
                                    'slug' => $cat['slug'],
                                    'page' => $currentPage - 1,
                                    'language' => $this->config->lang
                                ]);
                            }

                            ?>" aria-label="<?php echo $t->_('back') ?>">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    <?php endif ?>
                    <?php foreach($pages as $pageNumber): ?>
                        <li<?php if ($currentPage == $pageNumber): ?> class="active"<?php endif ?>>
                            <?php if ($currentPage == $pageNumber): ?>
                                <span><?php echo $pageNumber; ?></span>
                            <?php else: ?>
                                <a href="<?php

                                if ($pageNumber == 1) {
                                    echo $this->url->get([
                                        'for' => 'category',
                                        'slug' => $cat['slug'],
                                        'language' => $this->config->lang
                                    ]);
                                } else {
                                    echo $this->url->get([
                                        'for' => 'category_page',
                                        'slug' => $cat['slug'],
                                        'page' => $pageNumber,
                                        'language' => $this->config->lang
                                    ]);
                                }

                                ?>"><?php echo $pageNumber ?></a>
                            <?php endif ?>

                        </li>
                    <?php endforeach ?>
                    <?php if ($currentPage < $maxPages): ?>
                        <li>
                            <a href="<?php echo $this->url->get([
                                'for' => 'category_page',
                                'slug' => $cat['slug'],
                                'page' => $currentPage + 1,
                                'language' => $this->config->lang
                            ]) ?>" aria-label="<?php echo $t->_('forward') ?>">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    <?php endif ?>
                </ul>
            <?php endif ?>
            <div class="clearfix"></div>
        </div>
    </div>
</div>