<!-- PAGE HEADER
    ============================== -->
<?php $this->partial("widgets/page_header", [
    'header' => $cat['name'],
    'breadcrumbs' => [
        $cat['name']
    ]
]);

?>

<!-- PAGE CONTENT
============================== -->
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-2">

            <!-- Gategories -->
            <h3 class="header"><?php echo $t->_('cat_list') ?></h3>

            <div class="list-group list-group-left ui__sidebar nav affix-top" id="moving-menu" data-spy="affix">
                <?php foreach ($cats as $_cat): ?>
                    <a href="<?php echo $this->url->get([
                        'for' => 'category',
                        'slug' => $_cat['slug'],
                        'language' => $this->config->lang
                    ]) ?>"
                       class="list-group-item<?php if ($_cat['id'] == $cat['id']): ?> active<?php endif ?>"><?php echo $_cat['name'] ?></a>
                <?php endforeach ?>
            </div>
            <!--  / .list-group -->
        </div>
        <div class="col-sm-9 col-md-10">

            <div class="blog__items">
                <?php if ($docs): ?>
                    <?php foreach ($docs as $doc): ?>
                        <div class="blog__item">
                            <img src="<?php echo $doc['preview_image'] ? $doc['preview_image'] : '/img/general_doc_preview.jpg' ?>" alt="<?php echo $t->_('preview') . ' ' . $doc['name'] ?>" class="img-responsive blog__img hidden-xs">

                            <div class="blog__content">
                                <h3 class="blog__title">
                                    <?php echo $this->tag->linkTo([
                                        [
                                            'for' => 'doc',
                                            'language' => $this->config->lang,
                                            'cat_slug' => $cat['slug'],
                                            'doc_slug' => $doc['slug']
                                        ],
                                        $doc['name']
                                    ]) ?>
                                </h3>
                                <ul class="blog__info">
                                    <?php
                                    $doc['time'] = strtotime($doc['created_at']);
                                    ?>
                                    <li>
                                        <time datetime="<?php echo date('Y-m-d', $doc['time']) ?>"><?php echo date('Y-m-d', $doc['time']) ?></time>
                                    </li>
                                    <li>
                                        <a href="<?php echo $doc['discuss_url'] ? $doc['discuss_url'] : '#discuss' ?>"><i class="fa fa-comments-o"></i> <?php echo $t->_('discuss') ?></a>
                                    </li>
                                </ul>
                                <div class="blog__body">
                                    <?php echo $doc['text'] ?>
                                </div>
                            </div>
                        </div> <!-- / .blog__item -->
                    <?php endforeach ?>
                <?php else: ?>
                    <div class="blog__item">
                        <div class="blog__item"><?php echo $t->_('docs_no_found') ?></div>
                    </div>
                <?php endif ?>
            </div>
            <!-- / .blog__items -->
            <!-- Pager TODO: create pagination for documents view -->
            <!--ul class="pager pull-right">
              <li class="disabled"><a href="#">Previous</a></li>
              <li><a href="#">Next</a></li>
            </ul-->
            <div class="clearfix"></div>
        </div>
    </div>
</div>