<style>
	.nav-tabs {
		border-radius: 3px 3px 0 0;
		box-shadow: none;
		border: 1px solid #ccc;
	}

	.nav-tabs li.active {
		box-shadow: 0 2px 0 #fff;
	}

	.tab-content {
		border: 1px solid #ccc;
		overflow: hidden;
		padding: 5px 20px;
		border-top: none;
		border-radius: 0 0 3px 3px;
	}
</style>


<div class="page-header">
	<h3>Изменить "<?php echo $doc['translation'][$this->config->lang]['name'] ?>"</h3>
</div>

<ol class="breadcrumb">
	<li><a href="/<?php echo $this->config->lang ?>/admin">Главная</a></li>
	<li><a href="/<?php echo $this->config->lang ?>/admin/document/list">Документы</a></li>
	<li class="active"><?php echo $doc['translation'][$this->config->lang]['name'] ?></li>
</ol>

<div>
	<form action="/<?php echo $this->config->lang ?>/admin/document/edit/<?php echo $doc['id'] ?>" method="post" class="form-horizontal">
		<input type="hidden" name="doc[id]" value="<?php echo $doc['id'] ?>">
		<div class="form-group">
			<label for="slug" class="col-sm-2 control-label">Slug</label>
			<div class="col-sm-10">
                <input type="text" class="form-control" id="slug" disabled="disabled" value="<?php echo $doc['slug'] ?>">
                <input type="hidden"  name="doc[slug]" value="<?php echo $doc['slug'] ?>">
			</div>
		</div>

        <div class="form-group">
            <label for="category" class="col-sm-2 control-label">Категория</label>
            <div class="col-sm-10">
                <select class="form-control" id="category" name="doc[category_id]">
                    <?php foreach($cats as $cat): ?>
                        <option value="<?php echo $cat['id'] ?>"<?php if($cat['id'] == $doc['category_id']): ?> selected="selected"<?php endif?>><?php echo $cat['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>

		<div class="form-group">
			<label class="col-sm-2 control-label">Перевод</label>
			<div class="col-sm-10">
				<ul class="nav nav-tabs" role="tablist">
					<?php foreach ($doc['translation'] as $docTranslationLang => $docTranslation): ?>
						<li role="presentation"<?php if ($docTranslationLang == $this->config->lang): ?> class="active"<?php endif ?>><a href="#translation-<?php echo $docTranslationLang ?>" aria-controls="home" role="tab" data-toggle="tab"><?php echo strtoupper($docTranslationLang) ?></a></li>
					<?php endforeach ?>
				</ul>

				<div class="tab-content">
					<?php foreach ($doc['translation'] as $docTranslationLang => $docTranslation): ?>
					<div role="tabpanel" class="tab-pane<?php if ($docTranslationLang == $this->config->lang): ?> active<?php endif ?>" id="translation-<?php echo $docTranslationLang ?>">
						<input type="hidden" name="doc[translation][<?php echo $docTranslationLang ?>][id]" value="<?php echo $docTranslation['id'] ?>">
						<div class="form-group col-sm-12">
							<label for="name-<?php echo $docTranslationLang ?>" class="control-label">Название</label>
							<input type="text" class="form-control" id="name-<?php echo $docTranslationLang ?>" placeholder="Название" name="doc[translation][<?php echo $docTranslationLang ?>][name]" value="<?php echo $docTranslation['name'] ?>">
						</div>
						<div class="form-group col-sm-12">
							<label for="text-<?php echo $docTranslationLang ?>" class="control-label">Контент</label>
							<textarea class="form-control wysiwyg" id="text-<?php echo $docTranslationLang ?>" name="doc[translation][<?php echo $docTranslationLang ?>][text]" rows="3"><?php echo $docTranslation['text'] ?></textarea>
						</div>
					</div>
					<?php endforeach ?>
				</div>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-default">Сохранить</button>
				<a class="btn btn-secondary" href="/<?php echo $this->config->lang ?>/admin/document/list">Отмена</a>
			</div>
		</div>
	</form>
</div>