<!DOCTYPE html> 
<html lang="<?php echo $this->config->lang ?>">
    <head>

    <meta name="viewport" content="width=device-width, initial-scale=1,minimum-scale=1,maximum-scale=1">
    <link rel="shortcut icon" href="/favicon.ico">

        <meta charset="UTF-8">

        <meta name="keywords" content="" />
        <!--meta name="description" content="PlaceView.in – это web-платформа для создания (конструирования и администрирования), размещения и продвижения интерактивных виртуальных туров в сети Интернет. Платформа виртуальной реальности PlaceView.in способствует развитию рынка недвижимости, индустрии гостеприимства HoReCa, туризма и культуры, а так же многих других сфер бизнеса, для которых полезен визуальный образ места, как например автосалоны, магазины аксессуаров, развлекательные комплексы и пр." /-->
        <meta name="language" content="<?php echo $this->config->lang ?>" />
        <meta name="autor" content="<?php echo $_SERVER['HTTP_HOST'] ?>" />
        <!--meta name="title" content="Конструктор интерактивных витруальныx туров." /-->
        <!--meta name="og:title" content="Конструктор интерактивных витруальныx туров." /-->
        <meta name="og:type" content="website" />
        <meta name="og:url" content="<?php echo 'http' . (isset($_SERVER['HTTPS'])?  's' : '') . '://' . $_SERVER['HTTP_HOST'] ?>" />
        <meta name="og:image" content="<?php echo 'http' . (isset($_SERVER['HTTPS'])?  's' : '') . '://' . $_SERVER['HTTP_HOST'] ?>/img/logo_beta.png" />

        <?php $this->partial("widgets/meta/alternate"); ?>

        <?php
        $this->assets
            ->addCss('css/styles.css')
            ->addCss('css/animate.css')
            ->addCss('//fonts.googleapis.com/css?family=Open+Sans:400,300&subset=latin,cyrillic', false)
            ->addCss('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', false)
            ->addCss('css/placeview.css')
            ->collection('if lt IE 9')
                ->addCss('//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', false)
                ->addCss('//oss.maxcdn.com/respond/1.4.2/respond.min.js', false);
        ?>

        <!-- <link href='/assets/css/map.css' rel='stylesheet' /> -->
        <!-- CSS Global -->
        <?php $this->assets->outputCss() ?>

	    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
        <?php $this->assets->outputCss('if lt IE 9') ?>
	    <![endif]-->

        <script type="text/javascript" src="//code.jquery.com/jquery-2.1.4.min.js"></script>
        <?php $this->assets->outputJs() ?>

        <?php echo $this->tag->getTitle() ?>
    </head> 
    <body>      

    <!-- PRELOADER
    ============================== -->
    <div class="preloader">
      <img src="/img/preloader.gif" alt="<?php echo $t->_('loading') ?>" class="preloader__img">
    </div>

	<?php $this->partial("widgets/header"); ?>
   
	<?php echo $this->getContent() ?>

	<?php $this->partial("widgets/footer"); ?>
    
	<?php $this->assets->outputJs() ?>

    <script src="/js/bootstrap/bootstrap.min.js"></script>

	<!-- JS Plugins -->
    <script src="/js/smoothscroll.js"></script>
    <script src="/js/scrolltopcontrol.js"></script>
    <script src="/js/wow.min.js"></script>

    <!-- JS Custom -->
    <script src="/js/custom.js"></script>
    <script src="/js/custom_ui-nav.js"></script>
    <script src="/js/custom_info.js"></script>

    </body>
</html>