<!-- FOOTER
    ============================== -->
<footer>
    <div class="footer__hr hidden-xs"></div>

    <!-- Footer Bottom -->
    <div class="footer_bottom">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="footer__copyright"><?php echo $t->_('copyright') ?></div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="footer__language">
                        <label for="language"><?php echo $t->_('choose_lang') ?>:</label>
                        <select id="language" onchange="window.location.href = this.value;">
                            <?php foreach ($this->config->langs as $lang): ?>
                                <option
                                    value="<?php echo $this->extra->getUriInLang($lang) ?>"<?php if ($lang == $this->config->lang): ?> selected="selected"<?php endif ?>><?php echo $this->extra->getLanguageName($lang) ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </div>
            <!-- / .row -->
        </div>
        <!-- / .container -->
    </div>
    <!-- / .footer_bottom -->
</footer>