<!-- FOOTER
    ============================== -->
    <footer>

      
      <div class="footer__hr hidden-xs"></div>

      <!-- Footer Bottom -->
      <div class="footer_bottom">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-sm-4">
              <div class="footer__copyright">
                Copyright 2015
                <a href="http://placeview.in/">
                  Placeview.in
                </a>. All Rights Reserved.
              </div>
            </div>
              <div class="col-xs-12 col-sm-4">
                  <div class="footer__language">
                      <label for="language">Language:</label>
                      <select id="language" onchange="window.location.href = this.value;">
                          <?php $currentURI = $this->router->getRewriteUri() ?>
                          <?php foreach($this->config->langs as $lang): ?>
                          <option value="<?php echo str_replace("/{$this->config->lang}", "/{$lang}", $currentURI) ?>"<?php if($lang == $this->config->lang): ?> selected="selected"<?php endif ?>><?php echo strtoupper($lang) ?></option>
                          <?php endforeach ?>
                      </select>
                  </div>
              </div>
            <div class="col-xs-12 col-sm-4">
              <ul class="footer__social">
                <li class="twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li class="facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="linkedin"><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li class="google-plus"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li class="pinterest"><a href="#"><i class="fa fa-pinterest"></i></a></li>
              </ul>
            </div>
          </div> <!-- / .row -->
        </div> <!-- / .container -->
      </div> <!-- / .footer_bottom -->
    </footer>