<!-- FOOTER
    ============================== -->
<footer>
    <div class="footer__hr hidden-xs"></div>

    <!-- Footer Bottom -->
    <div class="footer_bottom">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="footer__copyright"><?php echo $t->_('copyright') ?></div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="footer__language">
                        <div class="dropup">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?php echo $this->extra->getLanguageName($this->config->lang) ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <?php foreach ($this->config->langs as $lang): ?>
                                    <li<?php if ($lang == $this->config->lang): ?> class="disabled"<?php endif ?>><a href="<?php echo $this->extra->getUriInLang($lang) ?>"><?php echo $this->extra->getLanguageName($lang) ?></a></li>
                                <?php endforeach ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- / .row -->
        </div>
        <!-- / .container -->
    </div>
    <!-- / .footer_bottom -->
</footer>