 <div class="navbar__hr hidden-xs hidden-sm"></div>

    <!-- STATIC NAVBAR
    ============================== -->
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <!-- Brand name -->
          <a class="navbar-brand" href="<?php echo $this->extra->url([
              'for' => 'home',
              'language' => $this->config->lang
          ]) ?>">
            <img src="/img/logo_beta.png">
          </a>
        </div>
      </div> <!-- / .container -->
    </div> <!-- / .navbar -->