<div class="page__header">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="page-header__title"><i class="fa <?php if(isset($icon)) { echo $icon; } else { echo 'fa-tag'; } ?>"></i> <?php echo $header ?></h3>
                <?php if(isset($breadcrumbs)): ?>
                <ol class="breadcrumb page-header__breadcrumb">
                    <li><a href="<?php echo $this->extra->url([
                            'for' => 'home'
                        ]) ?>"><?php echo $t->_('Home') ?></a></li>
                    <?php for($i = 0, $c = count($breadcrumbs); $i < $c; $i++): ?>
                        <li<?php if($i == $c - 1): ?> class="active"<?php endif ?>>
                            <?php if(is_array($breadcrumbs[$i])): ?>
                                <a href="<?php echo $breadcrumbs[$i]['link'] ?>"><?php echo $breadcrumbs[$i]['name'] ?></a>
                            <?php else: ?>
                                <?php echo $breadcrumbs[$i] ?>
                            <?php endif ?>
                        </li>
                    <?php endfor ?>
                </ol>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>