<?php
$menu = [
	'/' . $this->config->lang . '/admin' => 'Главная',
	'/' . $this->config->lang . '/admin/category/list' => 'Категории',
	'/' . $this->config->lang . '/admin/document/list' => 'Документы'
];
?>
<div class="container">
	<?php $this->flash->output() ?>

	<?php if ($this->user->isAdmin()): ?>
	<ul class="nav nav-pills">
		<?php foreach ($menu as $menuItemLink => $menuItemName): ?>
		<li<?php if ($menuItemLink == $this->router->getRewriteUri()):?> class="active"<?php endif ?>><a href="<?php echo $menuItemLink ?>"><?php echo $menuItemName ?></a></li>
		<?php endforeach ?>
		<li class="navbar-right"><a href="/<?php echo $this->config->lang ?>/admin/logout">Выйти</a></li>
	</ul>
	<?php endif ?>

	<?php echo $this->getContent() ?>
</div>