<?php
$menu = [
	'/' . $this->config->lang . '/admin' => $t->_('home'),
	'/' . $this->config->lang . '/admin/category/list' => $t->_('cats'),
	'/' . $this->config->lang . '/admin/document/list' => $t->_('docs')
];
$this->assets
    ->addCss('js/fancybox/jquery.fancybox.css?v=2.1.5');
?>
<script src="/js/tinymce/tinymce.min.js"></script>
<script src="/js/fancybox/jquery.fancybox.pack.js"></script>
<script>
    tinymce.init({
        selector: "textarea.wysiwyg",theme: "modern",width: 680,height: 300,
        language: '<?php echo $this->config->lang ?>',
        plugins: [
            "advlist autolink link image lists charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking",
            "table contextmenu directionality emoticons paste textcolor filemanager"
        ],
        toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect",
        toolbar2: "| filemanager | link unlink anchor | image media | forecolor backcolor  | print preview code ",
        image_advtab: true ,

        external_filemanager_path:"/js/tinymce/plugins/filemanager/",
        filemanager_title: "<?php echo $t->_('filemanager') ?>" ,
        external_plugins: { "filemanager" : "/js/tinymce/plugins/filemanager/plugin.min.js"}
    });

    $('.fancybox').fancybox();

    $('.iframe-btn').fancybox({
        'width'     : 900,
        'height'    : 900,
        'type'      : 'iframe',
        'autoScale'	: false
    });
</script>
<div class="container">
	<?php $this->flash->output() ?>

	<?php if ($this->user->isAdmin()): ?>
	<ul class="nav nav-pills">
		<?php foreach ($menu as $menuItemLink => $menuItemName): ?>
		<li<?php if ($menuItemLink == $this->router->getRewriteUri()):?> class="active"<?php endif ?>><a href="<?php echo $menuItemLink ?>"><?php echo $menuItemName ?></a></li>
		<?php endforeach ?>
		<li class="navbar-right"><a href="/<?php echo $this->config->lang ?>/admin/logout"><?php echo $t->_('logout_btn') ?></a></li>
	</ul>
	<?php endif ?>

	<?php echo $this->getContent() ?>
</div>