<style>
	.nav-tabs {
		border-radius: 3px 3px 0 0;
		box-shadow: none;
		border: 1px solid #ccc;
	}

	.nav-tabs li.active {
		box-shadow: 0 2px 0 #fff;
	}

	.tab-content {
		border: 1px solid #ccc;
		overflow: hidden;
		padding: 5px 20px;
		border-top: none;
		border-radius: 0 0 3px 3px;
	}
</style>


<div class="page-header">
	<h3>Изменить "<?php echo $cat['translation'][$this->config->lang]['name'] ?>"</h3>
</div>

<ol class="breadcrumb">
	<li><a href="/admin">Главная</a></li>
	<li><a href="/admin/category/list">Категории</a></li>
	<li class="active"><?php echo $cat['translation'][$this->config->lang]['name'] ?></li>
</ol>

<div>
	<form action="/admin/category/edit/<?php echo $cat['id'] ?>" method="post" class="form-horizontal">
		<input type="hidden" name="cat[id]" value="<?php echo $cat['id'] ?>">
		<div class="form-group">
			<label for="slug" class="col-sm-2 control-label">Slug</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" id="slug" placeholder="Slug" name="cat[slug]" value="<?php echo $cat['slug'] ?>">
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-2 control-label">Перевод</label>
			<div class="col-sm-10">
				<ul class="nav nav-tabs" role="tablist">
					<?php foreach ($cat['translation'] as $catTranslationLang => $catTranslation): ?>
						<li role="presentation"<?php if ($catTranslationLang == $this->config->lang): ?> class="active"<?php endif ?>><a href="#translation-<?php echo $catTranslationLang ?>" aria-controls="home" role="tab" data-toggle="tab"><?php echo strtoupper($catTranslationLang) ?></a></li>
					<?php endforeach ?>
				</ul>

				<div class="tab-content">
					<?php foreach ($cat['translation'] as $catTranslationLang => $catTranslation): ?>
					<div role="tabpanel" class="tab-pane<?php if ($catTranslationLang == $this->config->lang): ?> active<?php endif ?>" id="translation-<?php echo $catTranslationLang ?>">
						<input type="hidden" name="cat[translation][<?php echo $catTranslationLang ?>][id]" value="<?php echo $catTranslation['id'] ?>">
						<div class="form-group col-sm-12">
							<label for="name-<?php echo $catTranslationLang ?>" class="control-label">Название</label>
							<input type="text" class="form-control" id="name-<?php echo $catTranslationLang ?>" placeholder="Название" name="cat[translation][<?php echo $catTranslationLang ?>][name]" value="<?php echo $catTranslation['name'] ?>">
						</div>
						<div class="form-group col-sm-12">
							<label for="description-<?php echo $catTranslationLang ?>" class="control-label">Описание</label>
							<textarea class="form-control" id="description-<?php echo $catTranslationLang ?>" placeholder="Описание" name="cat[translation][<?php echo $catTranslationLang ?>][description]" rows="3"><?php echo $catTranslation['description'] ?></textarea>
						</div>
					</div>
					<?php endforeach ?>
				</div>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-default">Сохранить</button>
				<a class="btn btn-secondary" href="/admin/category/list">Отмена</a>
			</div>
		</div>
	</form>
</div>