<div class="page-header">
    <h3><?php echo $isNew ? $t->_('cat_create') : $t->_('cat_edit', ['cat_name' => $cat['translation'][$this->config->lang]['name']]) ?></h3>
</div>

<ol class="breadcrumb">
    <li><a href="<?php echo $this->url->get("/{$this->config->lang}/admin") ?>"><?php echo $t->_('home') ?></a></li>
    <li><a href="<?php echo $this->url->get("/{$this->config->lang}/admin/category/list") ?>"><?php echo $t->_('cats') ?></a></li>
    <li class="active"><?php echo $isNew ? $t->_('new_doc') : $cat['translation'][$this->config->lang]['name'] ?></li>
</ol>

<div>
    <form action="<?php echo $this->url->get($isNew ? "/{$this->config->lang}/admin/category/create" : "/{$this->config->lang}/admin/category/edit/{$cat['id']}") ?>" method="post" class="form-horizontal">
		<input type="hidden" name="cat[id]" value="<?php echo $cat['id'] ?>">
		<div class="form-group">
			<label for="slug" class="col-sm-2 control-label">Slug *</label>
            <div class="col-sm-3">
                <input type="text" class="form-control" id="slug" disabled="disabled" value="<?php echo $cat['slug'] ?>">
                <input type="hidden" name="cat[slug]" value="<?php echo $cat['slug'] ?>">
                <?php if($isNew): ?><p class="help-block">Slug будет создан автоматически.</p><?php endif ?>
            </div>
		</div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Перевод *</label>
            <div class="col-sm-10">
                <ul class="nav nav-tabs" role="tablist">
                    <?php foreach ($this->config['langs'] as $lang): ?>
                        <li role="presentation"<?php if ($lang == $this->config->lang): ?> class="active"<?php endif ?>><a href="#translation-<?php echo $lang ?>" aria-controls="home" role="tab" data-toggle="tab"><?php echo strtoupper($lang) ?></a></li>
                    <?php endforeach ?>
                </ul>

                <div class="tab-content">
                    <?php foreach ($this->config['langs'] as $lang): ?>
                        <div role="tabpanel" class="tab-pane<?php if ($lang == $this->config->lang): ?> active<?php endif ?>" id="translation-<?php echo $lang ?>">
                            <input type="hidden" name="cat[translation][<?php echo $lang ?>][id]" value="<?php echo $cat['translation'][$lang]['id'] ?>">
                            <div class="form-group col-sm-12">
                                <label for="name-<?php echo $lang ?>" class="control-label">Название *</label>
                                <input type="text" class="form-control" id="name-<?php echo $lang ?>" placeholder="Название" name="cat[translation][<?php echo $lang ?>][name]" value="<?php echo $cat['translation'][$lang]['name'] ?>">
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="cat-<?php echo $lang ?>" class="control-label">Описание *</label>
                                <textarea class="form-control wysiwyg" id="cat-<?php echo $lang ?>" name="cat[translation][<?php echo $lang ?>][description]" rows="3"><?php echo $cat['translation'][$lang]['description'] ?></textarea>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default"><?php echo $isNew ? 'Создать' : 'Сохранить' ?></button>
                <a class="btn btn-secondary" href="<?php echo $this->url->get("/{$this->config->lang}/admin/category/list") ?>">Отмена</a>
            </div>
        </div>
	</form>
</div>