<div class="page-header">
	<h3><?php echo $t->_('cat_list') ?></h3>
</div>

<ol class="breadcrumb">
	<li><a href="/<?php echo $this->config->lang ?>/admin"><?php echo $t->_('home') ?></a></li>
	<li class="active"><?php echo $t->_('cats') ?></li>
</ol>

<table class="table table-striped table-hover table-bordered">
	<thead>
		<tr>
            <th><?php echo $t->_('id') ?></th>
            <th><?php echo $t->_('name') ?></th>
            <th><?php echo $t->_('slug') ?></th>
            <th><?php echo $t->_('created') ?></th>
            <th><?php echo $t->_('actions') ?></th>
		</tr>
	</thead>
	<tbody>

		<?php foreach ($cats as $cat) { ?>
		<tr>
			<td><?php echo $cat['id'] ?></td>
			<td><?php echo $cat['name'] ?></td>
			<td><?php echo $cat['slug'] ?></td>
			<td><?php echo $cat['created_at'] ?></td>
			<td>
				<a class="btn btn-default btn-xs" href="/<?php echo $this->config->lang ?>/admin/category/edit/<?php echo $cat['id'] ?>"><?php echo $t->_('edit') ?></a>
				<a class="btn btn-default btn-xs btn-danger" href="/<?php echo $this->config->lang ?>/admin/category/delete/<?php echo $cat['id'] ?>" onclick="return confirm('<?php echo $t->_('confirm_cat_delete', [
                    'cat_id' => $cat['id']
                ]) ?>');"><?php echo $t->_('delete') ?></a>
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<?php if ($maxPages > 1): ?>
<nav>
	<ul class="pagination">
		<?php if ($currentPage > 1): ?>
		<li>
			<a href="/<?php echo $this->config->lang ?>/admin/category/list/<?php echo $currentPage - 1 ?>" aria-label="<?php echo $t->_('back') ?>">
				<span aria-hidden="true">&laquo;</span>
			</a>
		</li>
		<?php endif ?>
		<?php foreach($pages as $pageNumber): ?>
			<li<?php if ($currentPage == $pageNumber): ?> class="active"<?php endif ?>>
				<?php if ($currentPage == $pageNumber): ?>
					<span><?php echo $pageNumber; ?></span>
				<?php else: ?>
					<a href="/<?php echo $this->config->lang ?>/admin/category/list/<?php echo $pageNumber ?>"><?php echo $pageNumber ?></a>
				<?php endif ?>

			</li>
		<?php endforeach ?>
		<?php if ($currentPage < $maxPages): ?>
		<li>
			<a href="/<?php echo $this->config->lang ?>/admin/category/list/<?php echo $currentPage + 1 ?>" aria-label="<?php echo $t->_('forward') ?>">
				<span aria-hidden="true">&raquo;</span>
			</a>
		</li>
		<?php endif ?>
	</ul>
</nav>
<?php endif ?>
<a class="btn btn-primary" href="/<?php echo $this->config->lang ?>/admin/category/create"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $t->_('create') ?></a>