<h3>Логин</h3>

<div class="panel panel-default">
    <div class="panel-body">
        <?php echo $this->tag->form('admin/login') ?>
            <label for="email">Username</label>
            <?php echo $this->tag->textField(array("username", "size" => "30")) ?>
            <br />
            <label for="password">Password</label>
            <?php echo $this->tag->passwordField(array("password", "size" => "30")) ?>
            <br />
            <?php echo $this->tag->submitButton(array('Войти')) ?>
            <p>
                <div id="message"><?php echo $message ?></div>
            </p>
        </form>
    </div>
</div>